### ISSUE TITLE
about Charm: Friendly

### ISSUE THREAD

**Issue by Ayukawayen** [hashdragons/hashdragons.io#2]
Charm | < 5 | Brutal
-- | -- | --
  | < 15 | Unfriendly
  | > 250 | Friendly
  | > 230 | Charming
  | > 250 | Shimmering

Is it a typo? I think >200 = Friendly is more reasonable.

**Comment by AllanCat** [comment]
Also the following two descriptions:
Inner Light - Genius if >255
Magic - Mythical if >255
while the max value you can get is 255(ff)
I guess it should be = 255 here.

**Comment by zeptochain** [comment]
Fixes made and page updated. Also realized I had the descriptions for "presence" in the wrong order (since that byte is the alpha value of the color byte RGBA).
